apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: layers-simple-tap-development
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/marrober/layers-simple-tap-development@sha256:165045cf3ef44bfb59d98861b23ccb95650026e0f50df2cdcc2a239ea9e18807
        name: container-image
        resources: {}
status: {}
