apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: layers-simple-tap-development
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-marrober-tenant/tap-development/layers-simple-tap-development@sha256:b361e127589523c8217547dc034f3eb8f596ba5f13b29f1e865aa73c5990da6a
        name: container-image
        resources: {}
status: {}
