apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: layers-simple-tap-development
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-marrober-tenant/tap-development/layers-simple-tap-development@sha256:a21444b1a8b784fc9572cdf7de76db36651bf9955e286acc7588f9a8bb0edbf3
        name: container-image
        resources: {}
status: {}
