apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: layers-simple-tap-development
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: layers-simple-tap-development
    app.kubernetes.io/part-of: tap-development
  name: layers-simple-tap-developoke6
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: layers-simple-tap-development
    weight: 100
status: {}
