apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: layers-simple-tap-development
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: layers-simple-tap-development
    app.kubernetes.io/part-of: tap-development
  name: layers-simple-tap-development
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: layers-simple-tap-development
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: layers-simple-tap-development
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-marrober-tenant/tap-development/layers-simple-tap-development@sha256:967e9b4756a42960fcd3e4b468fa7083a3ec7212f3661a05b1613cface1764ff
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
