apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: layers-simple-tap-development
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: layers-simple-tap-development
    app.kubernetes.io/part-of: tap-development
  name: layers-simple-tap-development
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: layers-simple-tap-development
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: layers-simple-tap-development
    spec:
      containers:
      - image: quay.io/marrober/layers-simple-tap-development@sha256:165045cf3ef44bfb59d98861b23ccb95650026e0f50df2cdcc2a239ea9e18807
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
