apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: layers-simple-tap-development
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: layers-simple-tap-development
    app.kubernetes.io/part-of: tap-development
  name: layers-simple-tap-development
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: layers-simple-tap-development
status:
  loadBalancer: {}
